language: go

go:
- 1.12.x

env:
- GO111MODULE=on

sudo: false

install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls
  - mkdir -p $GOPATH/src/github.com/lonnblad
  - cd $GOPATH/src/github.com/lonnblad/go-oc-aws-tracing

script:
  - golangci-lint run ./...
  - overalls -project=github.com/lonnblad/go-oc-aws-tracing -covermode=count -ignore='.git,vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)