language: go
go:
- 1.11.x
- 1.12.x
- 1.13.x

os:
  - linux
  - osx
dist: trusty
sudo: false

install:
  - env GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - env GO111MODULE=on go get -u github.com/go-playground/overalls
  - env GO111MODULE=on go get -u github.com/mattn/goveralls

script:
  - golangci-lint run ./...
  - overalls -project=github.com/lonnblad/go-oc-aws-tracing -covermode=count -ignore='.git,vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic
  - env GO111MODULE=on go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)